### ISSUE TITLE
Line spacing issue in Tiro Kannada

### ISSUE THREAD

**Issue by Etewilak** [TiroTypeworks/Indigo#17] opened 2022-06-02 12:51 UTC
When the sequence U+0CA1 U+0CCD U+0CA1 is entered, the last character does not appear completely:
![image](https://user-images.githubusercontent.com/55674356/171633168-f1927a94-c603-4d3f-9b7d-d3b3332a1e21.png)

**Comment by Etewilak** [comment] 2022-06-02 12:55
A similar issue also occurs in Tiro Telugu.

**Comment by tiroj** [comment] 2022-06-03 15:40
It looks like LibreOffice Writer is clipping at the OS/2 sTypoDescender metric (-245), and ignoring the OS/2 usWinDescent value (-694), which explicitly sets the non-clipping zone for descending glyphs and stacks. A similar thing happens in MS Word if linespacing is defined as a multiple of the font metrics (e.g. 1) rather than in some other way such as explicit leading.

One way around this is to change the sTypoAscender and sTypoDescender to equal the same heights as the usWinAscent and usWinDescent, and set the sTypoLineGap to zero. But I don’t like doing that because a) the different sets of metrics are different for a reason, b) software should stop getting it wrong, and c) the usWin metrics need to be adjustable in future if taller or deeper glyphs are added to a font, while the linespacing metrics should remain unchanged to avoid document reflow.

**Comment by tiroj** [comment] 2022-09-10 00:07
Further to this: have confirmed that in at least some of the Tiro Indic fonts the OS/2 sTypo metrics and usWin metrics do not sum to the same height, so I can’t fix this by matching the former to the latter without breaking document layout.

The other font side option would be to extend the sTypoAscender and sTypoDescender to sum to their current height plus the sTypoLineGap, and set the latter to zero.

Would still dearly love to see this fixed on the app side though!

**Comment by tiroj** [comment] 2022-09-10 00:38
Hmm. I don’t see a way to change the font metrics without causing document reflow at least somewhere in the web of dependencies across text layout environments.

So no change for v1.60 I think.

**Comment by vv-monsalve** [comment] 2022-09-11 20:37
@tiroj The latest VM tests I've done on all platforms led me to conclude that Word and Libre Office on Windows are indeed using typoMetrics instead of Win metrics.

@Etewilak In which version of Libre Office Writer is this happening? I can't replicate it in LibreOffice 7.4.0 (Windows 10), nor with LibreOffice 7.2.1.2 om MacOS Big Sur (11.6.5)

Tests done with TiroKannada-Regular.ttf v1.48. 

- Default "Simple" in Line spacing options in the Paragraph formatting

Windows
<img width="1397" alt="Screen Shot 2022-09-11 at 14 46 06" src="https://user-images.githubusercontent.com/48698976/189546909-5c569b7c-a5f3-490d-a6c9-d4680d907925.png">
Mac
<img width="1378" alt="Screen Shot 2022-09-11 at 15 22 53" src="https://user-images.githubusercontent.com/48698976/189547525-dfa504bc-2f2d-4b03-87cc-c20a13897094.png">


- Clipping only happens when the option is turned to "Fixed" at 12 pt (solid) Line spacing
<img width="1397" alt="Screen Shot 2022-09-11 at 14 47 05" src="https://user-images.githubusercontent.com/48698976/189546953-36674535-3a76-49c1-8422-674bd72e8a60.png">

**Comment by tiroj** [comment] 2022-09-12 15:04
Thanks for looking into this, Viviana. After reviewing the options, I’ve decided not to change the current metrics settings in the fonts, but will probably add something about vertical metrics to the documentation on which I’ve been working this summer, so that if someone wants to fork the fonts and apply different metrics they have an idea what the issues and options are.

**Closed** 2022-09-12 15:05 UTC
Labels: All Scripts

**Comment by vv-monsalve** [comment] 2022-09-12 15:36
> but will probably add something about vertical metrics to the documentation on which I’ve been working this summer, so that if someone wants to fork the fonts and apply different metrics they have an idea what the issues and options are.

Looking forward to seeing it. I've performed some VM tests to check current GF specifications and been documenting them in [this doc](https://docs.google.com/document/d/1qInflfGcPm1D0PWDAMfJmYs2ftMB5MWrhr-xo-9NSFM/edit) in case some of the findings could be of any help. Also, I have many open questions about some behaviors I don't get and will need to investigate further.
