### ISSUE TITLE
Telugu చై wrong rendering

### ISSUE THREAD

**Issue by sonymoparthi** [TiroTypeworks/Indigo#53] opened 2023-01-03 17:49 UTC
wrong display

'Tiro Telugu'

0C1A0C48

<img width="870" alt="wrong one" src="https://user-images.githubusercontent.com/9820231/210412771-d1d29e0e-42d6-473c-851f-b6c5bd2bce6a.png">

**Comment by tiroj** [comment] 2023-01-03 18:09
Error confirmed and being investigated (most likely a typo in the VOLT GSUB source). This is a critical bug, so I will fix it and push an update as quickly as possible, and will also notify Google Fonts and recommend a patch.

**Comment by sonymoparthi** [comment] 2023-01-03 18:25
Thanks for the quick response.

**Comment by tiroj** [comment] 2023-01-03 18:58
Bug turns out to be an outline error in the /tCai/ glyph (which is really disturbing, as this means that it presumably dates to the Murty Telugu work several years ago, and no one has spotted it until now!)

Working on fix.

**Comment by tiroj** [comment] 2023-01-03 19:41
Fixed in Telugu critical shape fixes commit. Sources and pre-built fonts updated.

**Closed by tiroj** 2023-01-03 19:41 UTC
Labels: Telugu

**Comment by tiroj** [comment] 2023-01-12 21:40
Please to report that this fix has now gone live in Google Fonts.
